package com.example.androidjannes.room

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters

/**
 * Entity class representing NBA seasons for offline usage in the local database.
 *
 * @param seasons List of NBA seasons stored in the database.
 * @param id Primary key auto-generated by the database.
 */
@Entity(tableName = "nbaSeasons")
data class Seasons(
    @TypeConverters(Converters::class)
    val seasons: List<Int>,
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0
)